### ISSUE TITLE
Build failures on macOS

### ISSUE THREAD

**Issue by patrickkamin** [nunchuk-io/nunchuk-desktop#1]
Hi,

first of all, thanks for making the code available. I'm trying to build the code on mac os, but was running into various build problems.

Looking at https://github.com/nunchuk-io/nunchuk-desktop/blob/main/nunchuck-client-qt.pro#L59, the instructions try to pull in code from contrib/nunchuk-client, but the submodule is named contrib/libnunchuk. There are various other places in the build script that refer to nunchuk-client. 
`    contrib/nunchuck-client/include/nunchuck.h \`

Is there newer code available that already fixes this?

**Comment by patrickkamin** [comment]
Ok building via CMake worked fine.

I went with the CommonCrypto for SqlCipher instead of Openssl. In case folks need the steps

`./configure --with-crypto-lib=commoncrypto --enable-tempstore=yes CFLAGS="-DSQLITE_HAS_CODEC -iframework /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks" LDFLAGS="-framework Security -framework Foundation"`

It does require linking at build time
**CMakeLists.txt**
`target_link_libraries (${PROJECT_NAME} "-framework CoreFoundation" "-framework Security" Qt5::Core Qt5::Gui Qt5::Qml Qt5::Quick )`

**Comment by tongvanlinh** [comment]
@patrickkamin sorry about that, currently it supports with CMake only and it doesn't work with qmake, I will remove qmake in next commit
