### ISSUE TITLE
Scanning of keystone qr fails 

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#13]
If I scan a signed  transaction airgapped with seedsigner it fails to scan and an error message pops up, within mobile app it scans/ signs successfully with same signer though. It seems to try multiple times on android and only once on windows,  hence it always fails to import the signed transaction...

**Comment by Funman2** [comment]
So i can scan now with linux ubuntu using Droidcam HD, but everytime it scans the seedsigner qr, I get this error message ( Happens always, i could scan 2 times in the beginning without error and broadcast the transaction, but then it started failing always!) On Android, same keys and wallets always scan sucessfully though even when executed on laptop in Bluestacks android player(virtual) it always scans sucessfully(!) even when using the shitty laptop low resolution HP webcam 50...
So this is a linux client problem, same happens on other windows machine, it always fails even with high resolution HD cams, it only scans once, then error.
Where on Android it keeps scanning until success always works there!
![Bildschirmfoto von 2022-07-07 09-38-38](https://user-images.githubusercontent.com/105175715/178807802-3478c040-4056-4c1f-be70-f05f781e8070.jpg)

**Comment by tongvanlinh** [comment]
@Funman2 thanks for your feedback, I'm on debugging for QR scan with keystone hardware. I will share you soon

**Comment by Funman2** [comment]
I am scanning with seedsigner though...

**Comment by tongvanlinh** [comment]
@Funman2 Can you try [this version](https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.10.2_linux/nunchuk-linux-1.9.10.2.zip) and see if it's any better?

**Comment by Funman2** [comment]
Will try tonight after work,  Europe time!  Thanks!

**Comment by Funman2** [comment]
HEY MAN YOU DID IT!! Wow great! It scans totally successful every single time now, I could immediately sign a multisig transaction with Seedsigner now, repeated the process 3 times to be sure, but I could now import the signed PSBT via QR without any failure every time! Guess you fixed it, congrats on your skills!
The only thing you should change is the success message from " import the successful"(wrong grammar) to "imported successfully" or " Import successful".
Great work! Now I can at least run Nunchuk Desktop on a virtual Linux machine!Awesome! Thx again.

**Comment by tongvanlinh** [comment]
@Funman2 thanks man :). Copy text is my mistake (copy but not fully ^^), I'll update soon. Official release will be soon as well

**Comment by Funman2** [comment]
One minor little thing for this version I saw: In the menu when creating a transaction the option to export QR  now only shows the text:"export to Keystone" not "export to keystone/seedsigner"
Thx again!
In my opinion this issue should be closed now,  no?

**Comment by tongvanlinh** [comment]
@Funman2 yeap, it can be closed, I will update the copy text. Thank for your feedback. If you face other issue, let me know,
