### ISSUE TITLE
Nunchuk desctop open GL Error

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#14]
If i try to install Nunchuk Desktop on Windows 10 i always get this error:
---------------------------
NunchukClient
---------------------------
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.
---------------------------
OK   
---------------------------

**Comment by tongvanlinh** [comment]
@Funman2 Did you have any solution to solve this one before ? And could you share me the result of it
I tried on many window (paid) and ít's work well. I think the graphics driver is not latest. (The other users also can run nunchuk on their window)

If you can share more infomation it can be easier to make other version for you

**Comment by Funman2** [comment]
No sorry, I  guess windows has no solution for the open gl problems with Intel drivers,  I was searching for hours to find a solution. On an other machine it worked for me as well. I guess I can't use nunchuk then on my windows. 
All other programs/apps have no graphics error though. 
I have no further information butn
 the error message I posted above when I start nunchuk.
Sorry! Thanks for your efforts.

**Comment by Funman2** [comment]
Dear Baron Tong,
my system specifications are:

Edition  Windows 10 Pro
Version                21H2
Installiert am     ‎19.‎05.‎2022
Betriebssystembuild     19044.1766
Leistung              Windows Feature Experience Pack 120.2212.4170.0

It is fully updated

And has:
Gerätename     Klemmstein-PC
Prozessor           Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz   2.50 GHz
Installierter RAM             8,00 GB (7,89 GB verwendbar)
Systemtyp          64-Bit-Betriebssystem, x64-basierter Prozessor
Stift- und Toucheingabe              Für diese Anzeige ist keine Stift- oder Toucheingabe verfügbar.

Grafics is Intel HD Graphics 3000, i tried 5 different driver versions including one custom made driver, no success. I also tried this solution but I might have done it wrong somehow, no result:
https://gist.github.com/rb-dahlb/26f316c5b6089807a139fc44ee69f0d1

Von: Baron Tong ***@***.***
Gesendet: Montag, 4. Juli 2022 18:15
An: nunchuk-io/nunchuk-desktop
Cc: Funman2; Mention
Betreff: Re: [nunchuk-io/nunchuk-desktop] Nunchuk desctop open GL Error (Issue #14)


@Funman2<https://github.com/Funman2> could you share me your window version ?
And when was your last update window ?

Select the Start button > Settings > System > About .

Open About settings

**Comment by Funman2** [comment]
I could finally start the app on windows by not using the latest intel driver but instead installing microsoft standard display driver on windows now.
But with this windows version of Nunchuk of course i still get the same scanning of QR issues as i had in Linux, which you already fixed here: https://github.com/nunchuk-io/nunchuk-desktop/issues/13
So I guss this also will work when you update the gerneral Nunchuk Version to optimised OR scanning, right?
Thx for your help.

**Comment by tongvanlinh** [comment]
@Funman2 yeap. Official release for window will be released on early next week or mid of next week. I will notify you as well

**Comment by Funman2** [comment]
Hey, I finally solved this issue completely on my own! Some google deep research digging for weeks and I found this hint: In Windows I went to:

 Open “Control Panel” and go to “System”.
 In the “System” window select “Advanced system settings”.
 Now, select “Environment Variables…”...here I added a new user variable value as “QT_OPENGL” as the “Variable name” and “desktop” as the “Variable value”.
And voila, the Nunchuk App opened with my Intel HD Graphics 3000 Driver installed!

Now I really look forward to next release of Nunchuk, without the QR scanning issues on Windows ( signing with Seedsigner still fails every time in windows version)
I hope this Information will help to see for you the nature of my open GL errors/issues...
Keep up the cool work!
Here is the link to the blog where I got my final hint on what was wrong with my open GL:
https://teamdrive.com/en/faq-en/opengl-direct3d-graphics-issue

**Comment by tongvanlinh** [comment]
@Funman2 1.9.11 was released on our [website](https://nunchuk.io/). Could you take a look and help me check on your linux and window ?
Thank you for your effort, if you have any question or need our help, please let me know

**Comment by Funman2** [comment]
Great news! Will for sure test and get back to you asap! Thanks for notifying me.

**Comment by Funman2** [comment]
Yes! Scanning of Seedsigner QR now works flawless on my Windows 10 pro as well as on my Linux Ubuntu 20.4 ! Even using my old HP laptop camera! No need for Droidcam either now. Well done thank you! 
Now can use it on my windows laptop without Linux or Android virtual machine.

I recently installed another version of Linux( Latest) and it could again not open the Nunchuk App image, will try that again, but I think as far as i understood, Ubuntu latest does not support app image anymore...have to check. But my Linux version runs fine now with Nunchuk!

2 little minor bugs I discovered: When adding wallet description in my wallets the date gets erased after each start of app, also when creating the wallet the description always gets erased.

I mobile app, the key date is shown wrong, I imported 8 different key one has 4 different derivations of same fingerprint, the data displayed by Nunchuk android app is always the same for each key( it stores them separately though under different names and handles them correctly when signing without errors, only data displayed is wrong). In Windows and Linux Key data is displayed in the correct way.

Should I open new GitHub issues for these?

Thanks a lot for all your improvements! Nunchuk app is the cooles looking wallet now, and that is very important for btc adoption!

**Comment by Funman2** [comment]
Yes! Scanning of Seedsigner QR now works flawless on my Windows 10 pro as well as on my Linux Ubuntu 20.4 ! Even using my old HP laptop camera! No need for Droidcam either now. Well done thank you!
Now can use it on my windows laptop without Linux or Android virtual machine.

I recently installed another version of Linux( Latest) and it could again not open the Nunchuk App image, will try that again, but I think as far as i understood, Ubuntu latest does not support app image anymore...have to check. But my Linux version runs fine now with Nunchuk!

2 little minor bugs I discovered: When adding wallet description in my wallets the data gets erased after each start of app, also when creating the wallet the description always gets erased.
In the android mobile app, the key data(xpub/derivatin/fingerprint) is shown wrong, I imported 8 different key one has 4 different derivations of same fingerprint, the data displayed by Nunchuk android app is always the same for each key tough( it stores them separately though under different names and handles them correctly when signing without errors, only data displayed is wrong). In Windows and Linux Key data is displayed in the correct way.

Should I open new GitHub issues for these?

Thanks a lot for all your improvements! Nunchuk app is the cooles looking wallet now, and that is very important for btc adoption!

Von: Baron Tong ***@***.***
Gesendet: Mittwoch, 27. Juli 2022 05:10
An: nunchuk-io/nunchuk-desktop
Cc: Funman2; Mention
Betreff: Re: [nunchuk-io/nunchuk-desktop] Nunchuk desctop open GL Error (Issue #14)


@Funman2<https://github.com/Funman2> 1.9.11 was released on our website<https://nunchuk.io/>. Could you take a look and help me check on your linux and window ?
Thank you for your effort, if you have any question or need our help, please let me know

**Comment by tongvanlinh** [comment]
@Funman2 thank you very much.
I will improve them. You can create to new issue and assign to me as well
And the data shown wrong in mobile I think it's sync problem. I will recheck also

**Comment by Funman2** [comment]
I also tried on my virtual mac os even there i could sign successfully with the new nunchuk desktop app  and webcam/seedsigner.... very cool.
