### ISSUE TITLE
Linux install fails Ubuntu

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#15]
I tried to run the App on Linux Ubuntu focal fossa, Appimage of the new Version creates Errror, some shared libraries are not found. Old Version 1.9.9 works. New one does not start. On Windows Nunchuk is the only app, wich does not start but produces several Open Gl Errors.

**Comment by Funman2** [comment]
Would be great! My workaround is running Nunchuk Android with Bluestacks Player now on Windows 10, Seedsigner signing and  scanning of PSBTs is working great now!Also on my Android device.
On Windows, I get the following Error Message when trying to start the App:
---------------------------
NunchukClient
---------------------------
Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) .
This is most likely caused by not having the necessary graphics drivers installed.

Install a driver providing OpenGL 2.0 or higher, or, if this is not possible, make sure the ANGLE Open GL ES 2.0 emulation libraries (libEGL.dll, libGLESv2.dll and d3dcompiler_*.dll) are available in the application executable's directory or in a location listed in PATH.

---------------------------
OK

I also tried to run the App on my Linux Virtual machine (Ubuntu 20.04.3 64 Bit), when starting the App Image nothing happens.( The Nunchuk 1.9.9 did run but had scanning issues. When I tra to run from Terminal I get this Error:


***@***.***:~/Applications$ ./nunchuk-linux-1.9.10_5535a2ef13d6ea21819865b553525447.AppImage

/tmp/.mount_nunchuuV2b9D/appdir/bin/nunchuk-client-qt: error while loading shared libraries: libqt5keychain.so.1: cannot open shared object file: No such file or directory ***@***.***:~/Applications$


Othewise, Nunchuk has a sleek design and is true Bitcoiner spirit, I like it a lot.
Also I wanted to report that I imported multiple keys with different derivations but the same Fingerprint manually, I can use them for different accounts of my trezor(use them airgaped with seedsigner), it works just fine and Nunchuk handeks them witout errors, but the xpub displayed on the keys description always shows the same info for 7 different keys, although it seems to be signing with the correct derivations each.
Thanks for your work!

Von: Hugo ***@***.***
Gesendet: Donnerstag, 30. Juni 2022 02:01
An: nunchuk-io/nunchuk-desktop
Cc: Funman2; Mention
Betreff: Re: [nunchuk-io/nunchuk-desktop] Linux install fails Ubuntu (Issue #15)


Thanks for reporting @Funman2<https://github.com/Funman2> . We'll take a look.

**Comment by tongvanlinh** [comment]
@Funman2 
Could you share detail error in your Ubuntu focal fossa ?

**Comment by Funman2** [comment]
I shared the linux error in my last reply in detail.
Thanks for open GL instructions,  tried many similar things already but no success so far will further investigate.So far nunchuk is the only app with this issue on my windows (Intel HD graphics 3000 latest  driver, )



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Baron Tong ***@***.***>
Datum: 30.06.22 16:15 (GMT+01:00)
An: nunchuk-io/nunchuk-desktop ***@***.***>
Cc: Funman2 ***@***.***>, Mention ***@***.***>
Betreff: Re: [nunchuk-io/nunchuk-desktop] Linux install fails Ubuntu (Issue #15)


@Funman2<https://github.com/Funman2>
Could you share detail error in your Ubuntu focal fossa ?

**Comment by Funman2** [comment]
I also tried to run the App on my Linux Virtual machine (Ubuntu 20.04.3 64 Bit), when starting the App Image nothing happens.( The Nunchuk 1.9.9 did run but had scanning issues. When I tra to run from Terminal I get this Error:


***@***.***:~/Applications$ ./nunchuk-linux-1.9.10_5535a2ef13d6ea21819865b553525447.AppImage

/tmp/.mount_nunchuuV2b9D/appdir/bin/nunchuk-client-qt: error while loading shared libraries: libqt5keychain.so.1: cannot open shared object file: No such file or directory ***@***.***:~/Applications$


Othewise, Nunchuk has a sleek design and is true Bitcoiner spirit, I like it a lot.

**Comment by tongvanlinh** [comment]
@Funman2 Thank you for your positive feedback on nunchuk
I wil fix Linux problem soon, with your info I saw it missed keychain lib, I will add and upload new patch version for linux and let you know later

**Comment by Funman2** [comment]
Awesome! Thank you!



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Baron Tong ***@***.***>
Datum: 30.06.22 16:57 (GMT+01:00)
An: nunchuk-io/nunchuk-desktop ***@***.***>
Cc: Funman2 ***@***.***>, Mention ***@***.***>
Betreff: Re: [nunchuk-io/nunchuk-desktop] Linux install fails Ubuntu (Issue #15)


@Funman2<https://github.com/Funman2> Thank you for your positive feedback on nunchuk
I wil fix Linux problem soon, with your info I saw it missed keychain lib, I will add and upload new patch version for linux and let you know later

**Comment by tongvanlinh** [comment]
@Funman2 sorry about that, it's not published. Please it on [HERE](https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.10.1_Linux/nunchuk-linux-1.9.10.1.zip)

**Comment by Funman2** [comment]
Now i get this Error:
freedom@freedom-VirtualBox:~/Downloads/nunchuk-linux-1.9.10.1$ ./nunchuk-linux-1.9.10.1.AppImage

(AppImageLauncher:11287): GLib-CRITICAL **: 10:06:59.307: g_file_test: assertion 'filename != NULL' failed
/tmp/.mount_nunchu0v9Gm3/appdir/bin/nunchuk-client-qt: error while loading shared libraries: libolm.so.3: cannot open shared object file: No such file or directory
freedom@freedom-VirtualBox:~/Downloads/nunchuk-linux-1.9.10.1$

**Comment by tongvanlinh** [comment]
@Funman2 I replace new one on [HERE](https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.10.1_Linux/nunchuk-linux-1.9.10.1.zip)  Please check it, it already had libolm

**Comment by tongvanlinh** [comment]
@Funman2 
About window, sure that I will try fix it soon, whren it done I will let you know

About QR: I know the problem because of camera's resolution on dessktop is not really good compare withmobile. Anyway, we also try to find the solution for this.
