### ISSUE TITLE
Wallet description gets erased after restart

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#18]
A minor Bug on Windows and Linux desktop app:

When adding wallet description in my wallets the data gets erased after each start of app, also when creating the wallet the description always gets erased. @barontongnunchuk @tongvanlinh did not manage to assign you somehow

**Comment by tongvanlinh** [comment]
@Funman2 please check on latest version

**Comment by Funman2** [comment]
Yes, that seems to be fixed successfully in latest version (nunchuk-windows-v1.9.13) !
Good job. Thx.
