### ISSUE TITLE
Multi Device Wallet does not sycn signed transactions

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#19]
Hey i just created a multi-device wallet as suggested by your website nunchuk.io here: https://resources.nunchuk.io/getting-started/multidevicemultisig/
I perceded as follows: i set up one desktop nuchuk client with one airgapped key and two other keys on 2 different mobile nunchuk android wallets.
I only imported one dirfferent key on each device, they all synced and the collab wallet showed the correct balcance/ transactions.
So i could open the chat with myself, and set up the multi device test wallet, but when trying to transact the signitures don't sync at all, i signed the same transaction in chat on each device, but the signitures dont sync.
I am connected to my own node.

**Comment by hugohn** [comment]
Hey @Funman2 what kinds of keys are you using specifically? Are the one on Android devices software keys? (If not, can you try to see if it works with software keys?)

**Comment by Funman2** [comment]
I was usig airgapped keys imported for an existing multisig testwallet...won#t use software wallet in real life for security issues but will give it a try and get back to you!
How long does the sync take ususally?

**Comment by hugohn** [comment]
Yes, just for testing to help us rule out the cause. Thank you.
It should happen right away if you sign via the chat. Almost instantly.

**Comment by Funman2** [comment]
Hey, I did create a software keys based collab-wallet and it did sync, I could successfully import the signed transaction in a multi device way via messenger and broadcast a transaction in a collaborative way as intended.

With airgapped keys it completly does not import the signed transactions via messenger at all, I even created a new wallet setting the multisig derivation path of the signers to: m/48'/0'/1'  with seedsigner export, as i thought maybe the sycn protocol does expect a certian derivation path or xpub model...

With custom derivation then Nunchuk could not read the animated QR Seedsigner was giving for custom path, while when i export standard derivation of seesigner (m/84'/0'/0'/2' ) for multisig it gives a static QR which Nunchuk can read...
Anyhow...after importing the xpubs and key data manually i could create the Multi device wallet and replicate it in Sparrow wallet, so i could fund it and was seeing the balance in Nunchuk, but signing with airgapped key is only possible with the airgapped key stored on the device. Then I sign on the other devices but the transaction does not combine the signatures with airgapped still. I tried two different setups, with each 2 of 3 Key multisig.

I would rather not use any kind of hot wallet, so as long as collaborative wallet does not support airgapped i can not use it.
Otherwise the concept is really brilliant and i hope it will be working one day for me!

But i still had the following errors/bugs in the process of creating software key based Multi Device Signer:
 I could not sign with the windows dektop wallet initially,it just refused to sign, second wallet created today i could sign with it. ( The desktop wallet set ecryption to messenger channels and then could not read the transactions anymore, when initializing the chat from mobile it worked the communication, i could see all messages on all devices but not sure if channels would be encrypted then, if not its a security no go in my eyes.... 

Then I first entered a passphrase on one of the keys in android, but then chose the option "I don't need a passprase" and skipped the passphrase, but still the key got created with passphrase, causing me a lot of headache to detect what i had enteres there...finally i solved it.

The dektop wallet does not stay signed in, every time i open the wallet i have to reenter credentials.

**Comment by hugohn** [comment]
@Funman2 thanks for testing it out. That sounds like a bug, you should be able to import signed transactions via QR code. We’ll look into it.

Just to make sure:
(a) your airgapped devices are all SeedSigners, correct?
(b) if you create a non-collaborative wallet (single sig or multisig) using your airgapped SeedSigner. Could you sign and import the transaction via QR code?

**Comment by hugohn** [comment]
We’ll look into the other issues separately as well. Thanks for reporting.

**Comment by Funman2** [comment]
Oh maybe i put in to much info in one comment:

Signing with seedsigner works flawless with guest mode and on accounts when i sign a transaction with the key i have set up, also key import works very well via seedsigner.

But syncing the signitures via messenger only workes with software keys. Not airgapped, although on the key data is shown correctly on all devices, also with the sync option it imports the keys. But the airgapped signed PSBTs just wont ever sync...

**Comment by hugohn** [comment]
Okay so it sounds like it’s only a problem within the messenger.

Does multisig with SeedSigners work for you too? without the chat/non-collaborative wallet.

**Comment by Funman2** [comment]
> Okay so it sounds like it’s only a problem within the messenger.
> 
> Does multisig with SeedSigners work for you too? without the chat/non-collaborative wallet.

Yes that works flawless since the latest updates!

**Comment by Funman2** [comment]
https://github.com/nunchuk-io/libnunchuk/issues/14
