### ISSUE TITLE
Transactions missing in Wallet history

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#21]
When signed in to guest mode, my main wallet only shows the transactions from this year(2022)! 
Transactions from 2021 are missing in wallet history under -->show all transactions
This happens no two different windows machines. Wallet balance is correct.

On Android it shows the transactions correctly.

**Comment by tongvanlinh** [comment]
@Funman2 could you check on latest version, is this working ?

**Comment by Funman2** [comment]
Sorry did not see this, but was solved in latest version (1.9.13)! THX
