### ISSUE TITLE
nunchuk-client-qt uses 20% GPU while doing nothing

### ISSUE THREAD

**Issue by Transisto** [nunchuk-io/nunchuk-desktop#22]
I launched the app and clicked "guest". Nothing more.

**Comment by elproducto** [comment]
Can confirm the same on Mac OS X

<img width="676" alt="Screen Shot 2022-08-23 at 7 20 40 PM" src="https://user-images.githubusercontent.com/3057562/186282918-3c471572-d06a-4c3f-822c-e870e3df85fe.png">

**Comment by hugohn** [comment]
Thanks for the report @Transisto @elproducto . We'll take a look.

**Comment by Transisto** [comment]
Was on windows for me.

**Comment by tongvanlinh** [comment]
@Transisto could you tell me some info:
- Which version did you check on it ?/
- Mainnet/testnet or signnet
- Is there any wallet/key/transaction ?
- How about it after 1 minute starting?
