### ISSUE TITLE
Seed entry needs improvement.

### ISSUE THREAD

**Issue by Transisto** [nunchuk-io/nunchuk-desktop#25]
When entering a word, the whole word has to be typed or keyboard/mouse has to be used to select the right word.

What it should do it auto-select the closest word, so that after 4 character the TAB or Space key can jump to next box.

Also there's an issue where autofill find words containing the string instead of starting with.
Example, The world is "identify" but typing "ident" brings up "accIDENT"
![image](https://user-images.githubusercontent.com/388716/197686871-528eaf0e-4203-44ef-b6a2-d13ac649d572.png)

Since no words contain a space character, the space key should jump to next box.

Copy pasting a seed with spaces could fit in all the boxes.

24th word could have the option to be calculated to be compatible with offline entropy generation.

![image](https://user-images.githubusercontent.com/388716/197687836-56fa9167-62de-4d0d-94a0-08898ef882a0.png)
When a seed fails the checksum it should stay filled so that it can be reviewed for errors.

**Comment by tongvanlinh** [comment]
Thank @Transisto , we've turning on this item also. Next version will be reflected

**Comment by Transisto** [comment]
It's better but not perfect yet,
![nunchuck seed](https://user-images.githubusercontent.com/388716/203883185-cc6ae713-1033-4aef-af37-14e068c62587.gif)

When there's enough character for only one world to be selected TAB should write that word then jump to next box.
Currently only jump to next box.

When there's enough character for only one world to be selected RETURN should write that word then jump to next box.
Currently only fill the word an say there.

When there's enough character for only one world to be selected SPACE should write that word then jump to next box.
Currently only write a space.

Not all of these need to work as described but there should be a way to type just enough letters plus a key to fill and jump to next..


For example this is how Electrum react to a TAB after any amount of letters.

![nunch seed elect](https://user-images.githubusercontent.com/388716/203883915-a302267b-c51e-46a4-9867-c48559df55f9.gif)

**Comment by Transisto** [comment]
Also if ever there's any typo, all 24 words still get cleared out.
![image](https://user-images.githubusercontent.com/388716/203884947-9208b519-1f0b-4517-a1bd-0a506bd29a9a.png)

**Comment by tongvanlinh** [comment]
@Transisto thank bro, we will make it more optimal and convenient. next version will be reflected
