### ISSUE TITLE
Error to add  Hardware key

### ISSUE THREAD

**Issue by d6n13l0l1v3r** [nunchuk-io/nunchuk-desktop#33]
When I try to add my ledger nano X key to the app show me this error when try to add the key

<img width="675" alt="image" src="https://user-images.githubusercontent.com/25048143/230787376-0979028d-77ff-4633-a316-69fa6be2735c.png">

this message is just after this screen 

<img width="639" alt="image" src="https://user-images.githubusercontent.com/25048143/230844836-9cdcaadd-4a6f-4f9b-9bf2-c897a59d602a.png">

Notes: 
- on the device don't appear nothing to sign approve,
- the hardware Key work property with sparrow wallet in same computer

MacOS Ventura 13.3.1
Nunchuck Desktop 1.9.17
Hardware key : Ledger Nano X

**Comment by merlinana** [comment]
@d6n13l0l1v3r Talk to Ledger Support on the [Ledger Live support](https://explore-ledger.online/) so that your issue can be looked into.

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**

**Comment by tongvanlinh** [comment]
@d6n13l0l1v3r we have new patch with hwi 2.1.1 version. Could you try on this issue?

https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.18/nunchuk-mac-.33.zip

**Comment by d6n13l0l1v3r** [comment]
I try it and have same error 

on the ledger screen don't arrive nothing 


update to this version 
<img width="317" alt="image" src="https://user-images.githubusercontent.com/25048143/231175376-df3c95cd-09b4-4da3-b4e9-d905b63c742d.png">

**Comment by tongvanlinh** [comment]
@d6n13l0l1v3r Could you check the firmware version on your Nano X ? 
Beside that: In macos, there are some libs are required (python and libusb) 
to install it, try these commands:
brew install libusb
brew install python

**Comment by d6n13l0l1v3r** [comment]
the library are already installed
```
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
Warning: libusb 1.0.26 is already installed and up-to-date.
To reinstall 1.0.26, run:
  brew reinstall libusb
Warning: python@3.11 3.11.3 is already installed and up-to-date.
To reinstall 3.11.3, run:
  brew reinstall python@3.11
~
```
 but I will re-install it again just in case 
![image](https://user-images.githubusercontent.com/25048143/231212226-3cabb23e-8c14-4676-a364-8adcf4a7e844.png)

about the version for my nanoX is :
 * bitcoin app 2.1.1 
 * firmware 2.1.0
 
 
 I don't find a log file to see if show something additional , it's possible to activate a debug?

**Comment by giahuy98** [comment]
With the new build (https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.18/nunchuk-macos-1.9.18.zip), please disable the "Custom HWI Driver" and then try again @d6n13l0l1v3r.

**Comment by d6n13l0l1v3r** [comment]
@giahuy98 now when try to search the ledger device show 

<img width="715" alt="image" src="https://user-images.githubusercontent.com/25048143/231364291-547a1fa6-037d-457f-90c6-36cfd88f7fed.png">

**Comment by giahuy98** [comment]
Could you please provide a screenshot of the 'Custom HWI Driver' setting, @d6n13l0l1v3r 
It should look like this:
![image](https://user-images.githubusercontent.com/100193713/231377177-05c0b3a7-5a94-404a-a37a-64f79a25e67b.png)

**Comment by d6n13l0l1v3r** [comment]
Sure, below all screen 

<img width="531" alt="image" src="https://user-images.githubusercontent.com/25048143/231435691-2d391698-2448-483c-a7ba-dbca3abba329.png">
<img width="757" alt="image" src="https://user-images.githubusercontent.com/25048143/231435732-7699895c-fd11-4a99-a803-e6e683d4498f.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/25048143/231435801-9c4bd7e2-396f-4f68-ad96-4a4cedc92a52.png">

<img width="916" alt="image" src="https://user-images.githubusercontent.com/25048143/231436483-6db24af1-f23e-47ef-8bad-5cec71e3d8c1.png">

**Comment by d6n13l0l1v3r** [comment]
@giahuy98 I install from the oficial repository with pip command like this 

```
pip3 install -U hwi

~ pip3 show hwi
Name: hwi
Version: 2.2.1
Summary: A library for working with Bitcoin hardware wallets
Home-page: https://github.com/bitcoin-core/HWI
Author: Andrew Chow
Author-email: andrew@achow101.com
License: MIT
Location: /usr/local/lib/python3.11/site-packages
Requires: bitbox02, cbor, ecdsa, hidapi, libusb1, mnemonic, pyaes, pyserial, typing-extensions
Required-by:

```

![image](https://user-images.githubusercontent.com/25048143/231511205-3fda0552-91fe-4901-b33e-2637d025faac.png)

**Comment by giahuy98** [comment]
What about this command @d6n13l0l1v3r? (hwi download from https://github.com/bitcoin-core/HWI/releases)
```
/Users/doliver/Downloads/hwi-2.2.1-mac-amd64/hwi --debug enumerate
```

**Comment by d6n13l0l1v3r** [comment]
I did other test set the custom path to 

/usr/local/bin/hwi

and test again and work 
![image](https://user-images.githubusercontent.com/25048143/231514152-8c8ac494-c586-4673-b04e-c3e767798c38.png)

![image](https://user-images.githubusercontent.com/25048143/231514400-8d7ea946-6b12-4722-8a58-e691d014c52c.png)

![image](https://user-images.githubusercontent.com/25048143/231514481-f2f299d6-b56c-407b-8f96-117c7761a80d.png)


![image](https://user-images.githubusercontent.com/25048143/231515363-9eada180-ee5f-4a2f-b4fc-28167fe94af1.png)

but tell me 
<img width="717" alt="image" src="https://user-images.githubusercontent.com/25048143/231515897-11395582-66f5-46da-8e92-a28d763166bf.png">

I think sometime this is normal but I prefer to wait because installing to many things without verify

**Comment by giahuy98** [comment]
> Now my doubt is why if I use packet from https://github.com/bitcoin-core/HWI/releases/ work and with the version embedded in Nunchuk not ?

It appears that the hwi tool you used, `/usr/local/bin/hwi` was installed via `pip3`, and not from the hwi release page at https://github.com/bitcoin-core/HWI/releases/. 

Based on the image you shared here: https://github.com/nunchuk-io/nunchuk-desktop/issues/33#issuecomment-1503794541, it seem like the hwi from the release page is also not working. Only your hwi installed from `pip3` is working. 

It's possible that your Mac, anti virus or other security measures are preventing Nunchuk from running hwi, even the one embedded within Nunchuk.

**Comment by d6n13l0l1v3r** [comment]
strange because I algo have sparrow and spectre and work well, I let see if other report same issue because I have default security from Mac and little snitch to filter outgoing traffic

**Comment by d6n13l0l1v3r** [comment]
@giahuy98 could you upload to release repo [SHA256SUMS.asc] for version [Nunchuk v1.9.18]

**Comment by giahuy98** [comment]
The checksum file has been uploaded, @d6n13l0l1v3r.

Regarding the HWI issues, it appears that the latest version (2.2.1) has some problems running on Mac M1. Sparrow is building their own HWI binary for M1 instead of using the one from the official release page, which could be a reason why it works.

**Comment by d6n13l0l1v3r** [comment]
@giahuy98 just let you know, my Macbook is 2017 intel cpu.

<img width="248" alt="image" src="https://user-images.githubusercontent.com/25048143/232382675-bf494b7d-e03e-4b82-b4ad-92265be2c46a.png">

**Comment by giahuy98** [comment]
Sorry @d6n13l0l1v3r.
We have only been able to reproduce the error when scanning Ledger using M1 with HWI 2.2.1.
We really appreciate it if you could download HWI 2.2.1 from the release page https://github.com/bitcoin-core/HWI/releases and run it in Terminal to see if any errors occur

```
/path/to/your/downloaded-and-unzip-hwi-2.2.1/hwi --debug enumerate
```

**Comment by d6n13l0l1v3r** [comment]
sure @giahuy98 

I download [hwi-2.2.1-mac-amd64.tar.gz ](https://github.com/bitcoin-core/HWI/releases/download/2.2.1/hwi-2.2.1-mac-amd64.tar.gz)

result 

```
~/Downloads/hwi-2.2.1-mac-amd64 ./hwi --debug enumerate
[38017] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ImportError: dlopen(/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so, 0x0002): tried: '/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so' (fcntl(fd, F_ADDFILESIGS_RETURN) failed with errno=7 in <FCF78D44-CB39-3D13-988F-D88C248A3D8C> '/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so', sliceOffset=0x00000000, codeBlobOffset=0x0000CD40, codeBlobSize=0x49545050), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so' (no such file), '/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so' (fcntl(fd, F_ADDFILESIGS_RETURN) failed with errno=7 in <FCF78D44-CB39-3D13-988F-D88C248A3D8C> '/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so', sliceOffset=0x00000000, codeBlobOffset=0x0000CD40, codeBlobSize=0x49545050), '/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so' (fcntl(fd, F_ADDFILESIGS_RETURN) failed with errno=7 in <FCF78D44-CB39-3D13-988F-D88C248A3D8C> '/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so', sliceOffset=0x00000000, codeBlobOffset=0x0000CD40, codeBlobSize=0x49545050), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so' (no such file), '/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so' (fcntl(fd, F_ADDFILESIGS_RETURN) failed with errno=7 in <FCF78D44-CB39-3D13-988F-D88C248A3D8C> '/private/var/folders/vg/gh08wlnd5rn3k_6drvzgdpc80000gn/T/_MEIZIJyih/lib-dynload/_struct.cpython-39-darwin.so', sliceOffset=0x00000000, codeBlobOffset=0x0000CD40, codeBlobSize=0x49545050)
[38017] Module object for pyimod01_archive is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod01_archive.py", line 27, in <module>
ModuleNotFoundError: No module named 'struct'
[38017] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 28, in <module>
ModuleNotFoundError: No module named 'pyimod01_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[38017] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

after that download https://github.com/bitcoin-core/HWI/releases/download/2.2.1/hwi-2.2.1.tar.gz 

result:

```
~/Downloads/hwi-2.2.1 ./hwi.py --debug enumerate
DEBUG:ledgercomm:=> b001000000
DEBUG:ledgercomm:<= 0107426974636f696e05322e312e310102 9000
DEBUG:ledgercomm:=> e105000100
DEBUG:ledgercomm:<= 0b675ab1 9000
WARNING:jade:No module named 'hwilib.devices.jadepy.jade_ble'
WARNING:jade:BLE scanning/connectivity will not be available
INFO:jade.tcp:Connecting to tcp:127.0.0.1:30121
DEBUG:root:Failed to connect to Jade simulator at tcp:127.0.0.1:30121
DEBUG:root:[Errno 61] Connection refused
[{"type": "ledger", "model": "ledger_nano_x", "label": null, "path": "DevSrvsID:4295015831", "fingerprint": "0b675ab1", "needs_pin_sent": false, "needs_passphrase_sent": false}]
```

**Comment by giahuy98** [comment]
Hi @d6n13l0l1v3r,
Could you please try this new build? We are using our self-built HWI in this version.
https://github.com/hadvluffy/macdeploynunchuk/suites/12474794572/artifacts/664846103

**Comment by d6n13l0l1v3r** [comment]
this version work perfect when I disable the "Custom HWI Driver"
disable the "Custom HWI Driver"

<img width="557" alt="image" src="https://user-images.githubusercontent.com/25048143/234472996-db812aa1-6e39-46aa-9111-385f8a67af66.png">
