### ISSUE TITLE
Wrong path installation for dmg packages

### ISSUE THREAD

**Issue by d6n13l0l1v3r** [nunchuk-io/nunchuk-desktop#34]
Last 2 release the dmg packet try to install to /System/Applications and this directory is restricted, the dmg package should go to /Applications ; also have  .fseventsd folder and it should not be there 

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/25048143/232239377-6456ddd6-08f7-45a0-8c60-29877a274166.png">

**Comment by tongvanlinh** [comment]
@d6n13l0l1v3r  I've re-uploaded new archives with new sign checksum

**Comment by d6n13l0l1v3r** [comment]
now is as expect
