### ISSUE TITLE
Signing in with primary key fails

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#35]
In Version 1.9.18 and Version 1.9.19 signing in with a primary key does not work anymore.
It used to work in prior versions just find, now after entering the primary key passphrase it doesn't do anything anymore...
In that account I am connected to my node.
Strange enough if i enter my credentials for primary account first and then go to guest mode it seem to be logged on as primary account....

**Comment by tongvanlinh** [comment]
I got it, we are checking on it

**Comment by Funman2** [comment]
Hey, no problem at all! I am glad to tell you this version now works for primary key account login again! Will test it out further now....
Thank you for your work.

**Comment by Funman2** [comment]
well now in latest android version i can not sign at all anymore, the button does not work, i will report in android forum.

**Comment by Funman2** [comment]
Two things I noticed: within primary account, the send button on the wallet tab does not do anything, so I only could send within the messenger, but then since i have only small funds in the test wallet I could not adjust the fee and therefore not able to create a transactions since fees are to high now...within android version i could make lower fees and create a transaction.

**Comment by tongvanlinh** [comment]
@Funman2 I got this issue, we already are checking this

**Comment by tongvanlinh** [comment]
@Funman2 Can you share more infomation about this case ? We tried through our primary accounts, but I can not indentify what wrong in this bahavior.
- Your wallet (when you send) is shared wallet ?
- And in wallet list, is there the icon shared wallet displayed on that wallet?

**Comment by Funman2** [comment]
when hit the send button it does not initiate the dialogue for creating a transaction, instead the button is dead. Yes it is a collab wallet. See Video.
[screen-capture (20).webm](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/9cc37305-fd31-4aa2-8aa7-e164d515d13e)

**Comment by Funman2** [comment]
Hey I just saw the prerelease of nunchuk desktop Version 1.9.19 you uploaded 2 day ago. It works now to change the fee settings and open the send button in wallet overview tab!
Congratulations! Also you seem to have improved the encryption workload of processor very much, before my laptop was working like crazy for almost a minute or so to decrypt the wallet and nunchuk app got stuck during the process, now it is in a usable state right away! 
That's such great progress! I will close this issue now as it is solved.
