### ISSUE TITLE
signed Transaction from Desktop does not import to mobile android

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#41]
With airgapped signature, the signature does not import to android app anymore. but signed tx from android do import in desktop app. Using primary account.

**Comment by tongvanlinh** [comment]
@Funman2 thank you, we're looking for it.

**Comment by Funman2** [comment]
by the way , really great upgrades in 1.9.19 and android ! I closed a lot of issues! performance a lot better!

**Comment by Funman2** [comment]
also I noticed canceling of transaction does not sync on any device either.

**Comment by tongvanlinh** [comment]
@Funman2 
Thank you very much for your your great contribution to nunchuk.
Hope that nunchuk will become your favorite wallet.  Generally I'm trying to handle sync issues between devices and platforms. It would be good soon

**Comment by tongvanlinh** [comment]
1.9.19 still on pre release version, you can use it as well, official version will  on next week with some other improvements

**Comment by Funman2** [comment]
Looking forward!  Nunchuk collab feature already is my favorite!  
The sync issue might be on the android app, because in desktop the signature from android imports just fine. 
Just the desktop signature does not import to android version. 
Anyway the fee adjustment now works. Also log in time much faster! You are most welcome for reporting, hope it helps.

**Comment by Funman2** [comment]
One more info for you: When I only had 2 devices logged into the primary account one other Windows machine and one android, the transaction imported into android from desktop and the other way round just fine, also canceling imported fine! 

Maybe I got some problems with old files in my windows installation? Should I try to clean the quotient data?
Whereas when I used 2 android and one desktop earlier today signed in simultaneously it did not import to android...

**Comment by tongvanlinh** [comment]
@Funman2 we're checking it. Pls don't remove your db. Because it may impact to encrypted (public key) in your account
We will inform soon

**Comment by Funman2** [comment]
Hey I tested new Version 1.9.20 it looks great! But still the signature from Desktop does not export to android after signing...only android does import to desktop.

**Comment by Funman2** [comment]
This morning I tested again with version 1.9.17. The TX imports to latest android version just fine! But with version 1.9.20 still no success.

**Comment by tongvanlinh** [comment]
@Funman2 we also debuging on this. Maybe it happend from our library. We will make patch fix for this

**Comment by Funman2** [comment]
Also I want to inform you, i tried , on another laptop with smaller screen (15``), Seedsigner won´t scan the QR code. _ had to magnify it, then it will scan.It would be nice to have a magnify Option for the QR window...
Where as on my 19`` screen laptop it scans without issues. Should I open another issue for this?

**Comment by Funman2** [comment]
Also i noticed in Version 1.9.20 after signing sucessfully, after closing the sign window, the desctop version does not show the signature in messenger! Only when switching to wallet tab. This might be the issue here. After restart of nunchuk it shows the signed tx in messenger but does not export...

**Comment by Funman2** [comment]
Hey, i saw you pushed a new version today. Unfortunately the signatures still don´t sync to android version once signed in desktop, using airgapped key.

**Comment by tongvanlinh** [comment]
@Funman2 can you share more info about:
- is it assisted wallet?
- primary account.
- step to issue
Please spport us thoes informations.

We tried some behavior that we thought same your case, but it's worked

**Comment by Funman2** [comment]
Hey sure, it´s a standard collab wallet with primary key as login.  No assist wallet. I tried my existing multisig with a 2 of 3 multisig setup, all 3 keys set up seperatly on 2 android devices and one windows desktop. 
Used seedsigner.
I tried this with 2 different primary accounts abd two different desktop machines also one linux vm, always same result. It used to work and still works just fine with verion 1.9.17 ...sync no problem. But in new versions since 1.19.19 it does not work anymore.

**Comment by tongvanlinh** [comment]
@Funman2 thank you. I will get more support from you soon, now we're checking base on your info.

**Comment by tongvanlinh** [comment]
@Funman2 Please help me check this on your case. [LINK HERE](https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.20/nunchuk-window-v1.9.20-pre7.zip)

**Comment by Funman2** [comment]
Hey success! It worked right away in this version!
Great, finally!
Loading time is a little longer for decrypting the app hangs quite for some time, but once everything is loaded it works fine now.
Thanks!!

**Comment by Funman2** [comment]
Tested one more time with other order with different android device and it also worked flawlessly! Congrats, looks like i can hodl now with nunchuk multisig collab! Awesome.

**Comment by tongvanlinh** [comment]
@Funman2 thank you. We will checkit in android version

**Comment by JayceLuong** [comment]
Hi @Funman2 Could you use Test net and send me the export file? I will try to import and debug.

**Comment by Funman2** [comment]
Hi @Jayce the key and the signature export now works fine in latest version pre7, just if I cancel a signed transaction it does not export from android to other devices, regardless if there other device is android or desktop. 
I never used testnet will try and debug but it will take some time since i am busy with my profession these days...
