### ISSUE TITLE
Can not log in anymore to primary account in version 1.9.20

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#46]
Hey, I just saw the newest release from 2 hours ago. In that version i can´t log in anymore after entering the passphrase for the primary account, it just remains on that screen, nothing happens, no log in...
i remember there was a similar issue in a prior version, dont remember which one it was...

**Comment by tongvanlinh** [comment]
@Funman2 I will update new one today.

**Comment by tongvanlinh** [comment]
@Funman2 I re-uploaded correct version. Previouse one is wrong branch target. Please help us check your case

**Comment by Funman2** [comment]
Hey, tested, signing in to primary account now works, but something is now completely wrong with database... first the transaction history was flashing back and forth every second, then finally showed only transactions from 2022...in wrong order...only one transaction from 2023 at the very end, many are missing.
Also it switched back to USD from Euro... also now in android it lacks the correct names of keys in android, now signature does export to android but does not import from android to desktop anymore! Thats a lot of bugs...

**Comment by Funman2** [comment]
the syncing was completly fine in last versions 1.9.20 from 2 weeks ago though.

**Comment by tongvanlinh** [comment]
@Funman2 
 first the transaction history was flashing back and forth every second, then finally showed only transactions from 2022...in wrong order...only one transaction from 2023 at the very end, many are missing.
 ==> Is that transaction short list at Home page, right ? Or even all transaction list screen (click "View All transactions"), data still missing.
 
 please help me check those information

**Comment by Funman2** [comment]
Yes shortlist is wrong and flashing back and forth after login for a minute,  then settles but still wrong. Entire history also wrong. That was not the case in prior version. 
Also syncing from andoid fails now.

**Comment by Funman2** [comment]
now second try the signatures did sync on all devices...could be i had an wifi issue on android befor, transactions are in weird order still, not sortable anymore in time order as it seems...

**Comment by tongvanlinh** [comment]
@Funman2 currently I have modified sort by status as default, you can sort by time in all transactions list, then sort list will be aligned

**Comment by Funman2** [comment]
Change of sort by time does not work,  if I click on it in all transactions list, it still mixes transaction in completely random order. 
Also sort by status does not make sense for me, very hard to find transactions if they are not in chronological order. 
Sort by time really should be by default. 
So I switched back to prior version because of this issue.

**Comment by tongvanlinh** [comment]
@Funman2 I've just updated pls check, still have one minor case is for txs has same blocktime value, sometime it still swap together, I'm improving it

**Comment by Funman2** [comment]
Will check!

**Comment by Funman2** [comment]
Yes Tx history seems fine now, also currency is correct. Sync of signatures works also fine!
Thanks for your efforts!

**Comment by Funman2** [comment]
Hey now the "hit enter" option is working for passphrase! Awesome! Could you also make this available this for entering encryprtion passphrase? That would be great!

**Comment by tongvanlinh** [comment]
@Funman2 Thank you, now we're make some improve following your suggestion before also.
If this issue work fine, can you close this one?
