### ISSUE TITLE
Signatures to verify downloadable files are incorrect

### ISSUE THREAD

**Issue by kustov404** [nunchuk-io/nunchuk-desktop#47]
Files with signatures assume that its sha256, but inside SHA256SUMS.asc 
Hash: SHA512

Also signature seems not to be valid:

Should be:
<img width="631" alt="image" src="https://github.com/nunchuk-io/nunchuk-desktop/assets/70959151/942a2018-c503-439c-849f-3fa29f8e4ec6">

I'm Getting:
![Untitled](https://github.com/nunchuk-io/nunchuk-desktop/assets/70959151/a4945324-5066-4e75-a630-f4fcd53f43d1)

**Comment by bakaoh** [comment]
hi @kustov404 , 
The checksums are sha256 hash
```
c25f7fa65b07162707831bbc5bcb849504355470c4de574627f7bbd3e0c0f174  nunchuk-linux-v1.9.20.zip
78c7c012d8f3a25148af6c81eca79e46397589bd1aa6c39fe2650a75c68ff0e9  nunchuk-macos-v1.9.20.zip
30941bd7a6e46ca9eb27329e65cd64015c1139c8fcad6e4b6943e109ea8d1bfd  nunchuk-window-v1.9.20.zip
```

This part in the file 
```
Hash: SHA512
```
is the algorithm that was used by GPG to hash text before sign

Curl seems can't download the file from github, try download file using browser or use wget
```
wget -qO - 'https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.20/nunchuk-macos-v1.9.20.zip' | shasum -a 256
78c7c012d8f3a25148af6c81eca79e46397589bd1aa6c39fe2650a75c68ff0e9  -
```

**Comment by kustov404** [comment]
Worked out just fine. Thanks
