### ISSUE TITLE
Pending Wallet Error in Version 1.9.21

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#49]
Hey Tong, I finally had time to install the new pre-release version 1.9.21.

Looking very good, 
neat design! But when signing in on windows, primary key account, collab wallet 2/3 wallet, airgapped keys, I get the following error message on main screen ( see screenshot).

It says pending wallet (But is finalized), but if I click on the pending wallet, it displays the wallet correctly as usual ( Wallet Name, TX, so on,  see 2nd Screenshot), otherwise, no errors on collab signing with messenger, as long as I set up the wallet fresh from scratch.
When using old database i could not log in to account (reported that issue, also had this error in prior versions), but with fresh database, no errors, and all signers work, multisig reconstructed, no problem.

![Nunchuk10-23](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/113f873f-66e5-4f05-b66b-9f5c49859f0d)

![Nunchuk2](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/2fc90b68-e9cb-499a-a2f8-e841d0016138)

On desktop I am using my own electrum server backend.

**Comment by Funman2** [comment]
Hey, still same issue in Version 1.9.22
![image](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/201df288-560f-4466-8e77-61b8970c6b51)

**Comment by barontongnunchuk** [comment]
@Funman2 I got it, I will fix on tomorrow version

**Comment by barontongnunchuk** [comment]
@Funman2 I saw, you ran on 1.9.21 as your capture ? Please make sure this still happened on 1.9.22 (still draft now)

**Comment by Funman2** [comment]
Yes I downloaded 1.9.22 and double checked twice,  but after installing it still says version i 
the new version 1.9.21,  maybe forgot change the numbers?

**Comment by tongvanlinh** [comment]
@Funman2 I've reup new version, pls help me check your case

**Comment by Funman2** [comment]
yes, preparing a celebration at home right now..Ii wanted to install, but then the checksum of version 1.9.22 does not correspond with the SHASUMS file...so i didn't want to take the chance. Could it be mixed up?

**Comment by Funman2** [comment]
installing now, did an error with checksum but got it right now, preparing a birthday party atm....so busy, but happy to help, will check later on

**Comment by Funman2** [comment]
Hey looking very good now, the pending wallet screen is not showing anymore, instead I can see my multisig collab wallet displayed as it should be.So Solved.

But with signing to primary account I noticed another new little issue/change:
 When first entering encryption password it does not display any blinking cursor anymore and also, after entering my password it gives an error message (see picture) but that does not prevent me from logging in...using enter key still not works, but clicking  on button still works fine. Thanks for your quick responses!
![image](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/fb5d2745-116a-441a-878c-0a8411cc5168)
![Nunchuk 1 9 22 log in](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/fbf002c1-d3c4-49c4-a8ad-f18b4a9c219e)

**Comment by Funman2** [comment]
When trying to sign a transaction with this new version i ran into another issue: The opening window on nunchuk app seems to be a little smaller now and seedsigner as well as jade where not able to read the qr anymore, i had to use the screen magnifier app to be able to scan qr, when i went back to prior version 1.9.20 it scanned just fine...

**Comment by barontongnunchuk** [comment]
@Funman2 thank you, happy birthday to you :). I'm preparing new patch on tomorrow, I'll let you know

**Comment by Funman2** [comment]
My sons birthday... but thanks!!

Don't get the reason why QR scan by seedsigner always fails now with new version,  did you change the density or information encoded or the refresh rate?

Or is it just the small size on my laptop (hp g7 2001sg 17" screen)...?
It used to work 100% fine in all prior 1.9.19, 1.9.20 versions...
So there was some change.... would be really nice in bitcoiner spirit if nunchuk would still work well on old hardware,  as it used to do, I need to stack sats not by new hardware, therefore I can't afford apple stuff;-)



Von meinem/meiner Galaxy gesendet



-------- Ursprüngliche Nachricht --------
Von: Baron Tống ***@***.***>
Datum: 27.10.23 10:50 (GMT+01:00)
An: nunchuk-io/nunchuk-desktop ***@***.***>
Cc: Funman2 ***@***.***>, Mention ***@***.***>
Betreff: Re: [nunchuk-io/nunchuk-desktop] Pending Wallet Error in Version 1.9.21 (Issue #49)


@Funman2<https://github.com/Funman2> thank you, happy birthday to you :). I'm preparing new patch on tomorrow, I'll let you know

**Comment by barontongnunchuk** [comment]
@Funman2 its mean, the QR shown on Nunchuk, and scan by seed signer camera (like capture)?  (I've changed refresh rate for this case)
Or scan QR by Nunchuk via your laotop camera with QR showing on seed signer?
<img width="1273" alt="image" src="https://github.com/nunchuk-io/nunchuk-desktop/assets/79987008/045ca9ed-9c28-4005-bc47-1e84e1033e80">

**Comment by Funman2** [comment]
> @Funman2 its mean, the QR shown on Nunchuk, and scan by seed signer camera (like capture)? (I've changed refresh rate for this case) Yes, seedsigner can´t read the displayed QR code by Nunchuk anymore, it´s always stuck at 6 or 17% maximum...the old setting/refreshrate of version 1.9.20 was readable 100 percent by seedsigner. So would ask you to go back to this setting if possible.

**Comment by barontongnunchuk** [comment]
@Funman2 I've reup for some bug fixed and QR change to origin refresh rate. Pls help me check

**Comment by Funman2** [comment]
Hey, happy to report that signing into encrypted primary account works without any errors now, also scanning and signing transaction with seedsigner works flawless again!

But now the old bug came back, where the signature from nunchuk mobile app does not import via messenger to desktop anymore...
this always used to work all the latest in prior versions.

**Comment by Funman2** [comment]
After trying a second time everything worked perfectly! 
( Importing and exporting to seedsigner, syncing signatures via messenger worked just perfect!)

**Comment by Funman2** [comment]
one more little feature request still , please allow me to hit the enter key on keyboard after entering wallet encrytion password ( enter the dragon), in the same manner as you integrated this to the Primary key passphrase entry, this is so much better without mouse usage...i hate mouse.;-)

Did some further test transactions yesterday evening, Nunchuk is now working so well and really is ready for practical use of multisig for serious BTC stashes! Will move soon (for my wife it´s still a little to complicated but will explain and convince...).

**Comment by tongvanlinh** [comment]
@Funman2 thx, I will improve soon wth your suggest. I think nunchuk still improve with user experience much more. Now we're rushing to finish our big feature, 
so, I will improve it soon
