### ISSUE TITLE
Typo in "Forgot my password" page

### ISSUE THREAD

**Issue by BitBoy14** [nunchuk-io/nunchuk-desktop#5]
Text says "We have sent a token to xxx@yyyy.zz. Please check it ou to change your password"

Please change "ou to" to "out to". See screenshot.

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/94248563/144903567-a0ff8228-aef6-41d7-8a8a-aeeab5161aaf.png">

**Comment by hugohn** [comment]
Fixed in latest build.
