### ISSUE TITLE
Windows 10 Trojan:Win32/Wacatac.B!ml

### ISSUE THREAD

**Issue by X-Hades-X** [nunchuk-io/nunchuk-desktop#61]
Getting a warning that Trojan:Win32/Wacatac.B!ml was found when installing on Windows 10

I hope it is a false positive but honestly no install from me as long as that is there.

**Comment by hugohn** [comment]
Can you share a screenshot? We've never heard of this. If it is true, it is a false positive.

**Comment by DestinyArrives6** [comment]
I confirmed, i got it too with the last release. I decided not to install it as well. Hope it is fixed soon.

**Comment by hugohn** [comment]
@DestinyArrives6 can you please share a screenshot?

So in previous version you didn’t see it, but in the latest version you do? what exact version are you running that you saw this issue?

It’s definitely a false positive.

**Comment by DestinyArrives6** [comment]
Yes, here it is. It's the first time I try to install it, so i don't know if there was anything similar in the previous version.
<img width="752" alt="Screenshot 2024-03-02 182216" src="https://github.com/nunchuk-io/nunchuk-desktop/assets/160147370/2f84d82d-f67e-414d-a1e2-2cedad6e5746">

**Comment by hugohn** [comment]
Could you please try the updated build? Thank you. @DestinyArrives6 @X-Hades-X 
https://github.com/nunchuk-io/nunchuk-desktop/releases/tag/1.9.29

**Comment by DestinyArrives6** [comment]
Hello, I've tried it right now, and got no issues this time. I've run a couple of tests but it seems to be ok. Thanks!

**Comment by hugohn** [comment]
Thanks for checking !
