### ISSUE TITLE
nunchuk-desktop download -> SHA256 hash doesn't match for "nunchuk-window-v1.9.30.zip"

### ISSUE THREAD

**Issue by 8tP24G** [nunchuk-io/nunchuk-desktop#62]
SHA256 hash doesn't match for "nunchuk-window-v1.9.30.zip" download

Hash that I calculate is:
61F72A7A9CBEEA4F57423396910759A1427D9796D14ACBF07BAE67DB51E9C3A9
Hash in the SHA256SUMS.asc file is:
78b63b5cbdd82db22779dae354e6bcad280a988981ac8cf9c23a9e2d4417e665

The hash for both "nunchuk-linux-v1.9.30.zip" and "nunchuk-macos-v1.9.30.zip" match perfectly.

**Comment by hugohn** [comment]
Fixed.
