### ISSUE TITLE
Mac app not usable on 13 inch screen

### ISSUE THREAD

**Issue by jurgen2005** [nunchuk-io/nunchuk-desktop#64]
Information at the bottom of the main window is not visible.
Window is not resizeable.

**Comment by jurgen2005** [comment]
Also mentioned here:
https://github.com/nunchuk-io/nunchuk-desktop/issues/38

**Comment by tongvanlinh** [comment]
@jurgen2005 pls check your issue on nunchuk latest version, We checked with our 13 inches screen

**Comment by jurgen2005** [comment]
fixed! great, thx!
