### ISSUE TITLE
Bitcoin address scanning fails, app chrashes

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#65]
Hey tested Version 1.9.32 on Linux, when I initiate a transaction in primary account multisig, I can't scan the address anymore, most of the times the app hangs and I have to force close it, sometimes it works, this used to be better in prior versions...
remote signing works really well though!
Also I miss the send button directly from messenger, it seems to be gone now. Also sometimes the transcation windows on the send window, just randomly scrolls through all past transactions while initiating a send, this seems to be a bug.
Otherwise great work!

**Comment by Funman2** [comment]
Hey, now i tried on Linux, the app chrashed right away when scanning, but second try it scanned, then i tried third time, it did not scan and when i tried to close, scan window hangs, pretty much the same behaviour as before, will try windows now.

**Comment by Funman2** [comment]
Tried windows now, on the HWI Version it detected a virus on the download ;-), this might just be a windows security issue!...on the regular version scanning of address works just fine, maybe it is a problem on my linux ubuntu and app image ...

**Comment by tongvanlinh** [comment]
@Funman2 pls try window version with hwi 2.1.1
Latest version happend warning because of hwi 2.4.0. We're still waiting for new version from hwi.

**Comment by Funman2** [comment]
Will try, away from keyboard now...

**Comment by Funman2** [comment]
So investigated thoroughly tonight, my findings: 
![Bildschirmfoto vom 2024-04-09 22-50-03](https://github.com/nunchuk-io/nunchuk-desktop/assets/105175715/dfe38a13-085e-4197-bfb4-d9c1418405ec)

I updated droidcam app wich i use for scanning on linux, no change
With new nunchuck versions 1.9.32 and 1.9.33, i can scan btc address when  sending in guest mode (encrypted database) But when logged in to primary key account ( encrypted database) scanning fails most of the times, nunchuck hangs.
Tried nunchuk 1.9.31 and it works fast and flawless, like it used to in the past. So you must have changed something. I Used a QR code from Sparrow wallet for BTC adress display. See attached image:

**Comment by tongvanlinh** [comment]
@Funman2 please help me check on this patch: https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.33/nunchuk-linux-v1.9.33.zip

**Comment by Funman2** [comment]
Hey, tried this new version, but still same bug, also now i updated udev rules and now i get a message "invalid signature" in nunchuk...

**Comment by Funman2** [comment]
tried on windows, scanning also fails in nunchuck 1.9.33

**Comment by tongvanlinh** [comment]
@Funman2 I still working on this. I'd like to confirm that you are scaning in Send flow, right?

**Comment by Funman2** [comment]
Yes

**Comment by tongvanlinh** [comment]
@Funman2 plse help me check on this linux version
https://github.com/nunchuk-io/nunchuk-desktop/releases/download/1.9.33/nunchuk-linux-v1.9.33.zip

**Comment by Funman2** [comment]
Now it got even weirder: first attempt, app did not even open scan window, freezed. Second time scan window opened(nice little red moving line..) did not freeze but did not scan any qr (stuck at 0% for minutes) . In Nunchuck 1.9.31 it scans within microseconds from sparrow.

**Comment by Funman2** [comment]
it seems to be more a problem of the app getting stuck when loading the messenger, maybe there are to many messages, would it help to delete the old chat?

**Comment by Funman2** [comment]
after deleting chat in new chat i could not do collab transactions anymore,

**Comment by Funman2** [comment]
so my conif is same primary key and username on 3 different devices, but i only could initiate a collab wallet with nunchuk 1.9.31 not with new version, also not with new mobile version, would i have to have different usernames then, to achieve this?Why did you remove this practical feature? Makes no sense...missing set up collab wallet option in new version. That was kind of the initial value proposition for nunchuk!...dont give it up please!

**Comment by hugohn** [comment]
@Funman2 Matrix-backed collaborative wallet is now available under Developer settings. You can enable it there.

**Comment by Funman2** [comment]
Thanks! Why are you hiding the most awesome feature of nunchuck? Hope not because you want to push users into a paid plan or assisted stuff, ...for me this is best option!

**Comment by hugohn** [comment]
It has been always an experimental feature. At times it can be unreliable due to the dependency on Matrix libraries. Hence we moved it to the Developer settings, so that beginner users don’t accidentally use it and make a mistake (quite a few have done so in the past).

**Comment by Funman2** [comment]
scanning now works after making new chat and wallet!

**Comment by Funman2** [comment]
> It has been always an experimental feature. At times it can be unreliable due to the dependency on Matrix libraries. Hence we moved it to the Developer settings, so that beginner users don’t accidentally use it and make a mistake (quite a few have done so in the past).

I noticed, setting up collab wallets work flawless when using the fingerprint of the primary key as a contact, but messenger is unreliable when only using the username of the account.
