### ISSUE TITLE
Backup Wallet File from iOS wont import into Linux Desktop App

### ISSUE THREAD

**Issue by jkinum** [nunchuk-io/nunchuk-desktop#7]
The 1.9.4  iOS client's exported BSMS wallet backup file does not import into the linux desktop client.  The root cause is that iOS saves it in a windows format line endings CR/LF and Linux just has LF line endings.  If you convert the iOS file to Linux LF line endings then the import works.

**Comment by hugohn** [comment]
@jkinum this should be fixed in the latest build. Could you help check?
