### ISSUE TITLE
Issues with Editing and Syncing Transaction Notes - MacOS Desktop App

### ISSUE THREAD

**Issue by guardianbitcoin** [nunchuk-io/nunchuk-desktop#71]
MacOS - Sonoma 14.5
Nunchuk - 1.9.36

Steps:
Open a transaction in the desktop app
Select the "edit/pencil" icon to add or edit a transaction note
All attempts to enter characters via the keyboard are not successful. Once typing begins the characters quickly disappear and any subsequent attempts result in the same behavior. Nothing can be saved or incomplete notes are saved at best.
Also, any edits to Transaction Notes via the mobile app (iOS) do not sync with the desktop app.

**Comment by tongvanlinh** [comment]
@guardianbitcoin let us check, can you tell me the "edit/pencil" you did on recieved transactions ?

**Comment by guardianbitcoin** [comment]
Tong, the issue appears to be fixed in the latest MacOS build, as I can no longer reproduce the error. Edits are now working as expected. Thanks!
