### ISSUE TITLE
Can't sign in with primary key in new version 1.9.41

### ISSUE THREAD

**Issue by Funman2** [nunchuk-io/nunchuk-desktop#74]
Hi, with the new version of Nunchuk Desktop, ( Linux Ubuntu 1.9.41) I can't even sign in anymore with my primary key account, after entering the Passphrase nothing happens. I remember this bug was also in some versions of the further past.

**Comment by Funman2** [comment]
After trying and restarting 3 timestime, it finally worked...seems to be some workload issue

**Comment by tongvanlinh** [comment]
@Funman2 Sometimes, a slow response from the network can affect your experience. Please try switching or checking your network connection.

**Comment by Funman2** [comment]
![grafik](https://github.com/user-attachments/assets/79b21751-c10d-40a8-b652-357e8d464d81)
I won't call that slow exactly but you are right, upload should be 50 Mbit/s my ISP is cheating on me again...as it seems but i am now checking hourly, so will not let them get away with it.
![grafik](https://github.com/user-attachments/assets/c200e5fb-0ba4-4c9f-adcc-0d7c99e0520b)
