### ISSUE TITLE
account login and wallet store identifier zero balance

### ISSUE THREAD

**Issue by jkinum** [nunchuk-io/nunchuk-desktop#8]
Successful login with zero balance can occur if the field "email address" is populated with upper case.   

OS: Linux
Version: Desktop 1.9.6 appimage

Steps to reproduce:
1.  create an account for xxx@email.com
2.  Create Keys, wallets etc under that account ID.
3. Log out.
4. log in with Xxx@email.com.  (note the capital letter)

Result: login is successful but keys, wallets and balances are missing.

Likely the result of how the wallet is stored in the file system via a hash of the email address.  When the email address is valid with a capital letter or the reverse then the hash also changes and the wallet is empty even with a valid login.

**Comment by hugohn** [comment]
thanks @jkinum for the report. looking into this.

**Comment by hugohn** [comment]
@jkinum this should also be fixed in the latest build.
